### PR TITLE
Port to Gtk3

### LINKED ISSUE #2: Port to GTK+ 3

### PR DESCRIPTION
**Pull request by chimosky**
Fixes #2

### CODE REVIEW

**Comment by chimosky** [comment]
@quozl kindly review

**Comment by quozl** [comment]
Thanks.  Tested on Ubuntu 18.04.  There's a CPU looping problem after starting the activity, it does not stop properly after stop button is pressed, and logs show a PyGIWarning for Gtk.

**Comment by chimosky** [comment]
> Thanks. Tested on Ubuntu 18.04. There's a CPU looping problem after starting the activity, it does not stop properly after stop button is pressed, and logs show a PyGIWarning for Gtk.

I did notice the looping problem, but no idea why as the logs didn't show anything unusual.

**Comment by quozl** [comment]
Thanks.  Presumably it is a logic problem, not a problem that logs errors.  Use a debugger.

**Comment by chimosky** [comment]
Will you merge the PR?

**Comment by quozl** [comment]
No, you need to fix the looping problem; it has potentially large consequences; users will lose stored energy in batteries, systems will get warm.

**Comment by quozl** [comment]
You might try these;

* add `print` statements to various class methods,
* use the pdb python debugger,
* check the sugar-docs repository for debugging,
* check the Wiki https://wiki.sugarlabs.org/go/Development_Team/Debugging

Also, carefully (on paper with diagrams if necessary) compare the program flow and structure between the Sugargame V1.2 test activity and this activity, working to change the structure accordingly; because I may have encountered this problem in other activities that ported to recent Sugargame, which suggests it is a pattern of code as root cause,

Or, if you really can't figure it out, look at _every_ recent commit to _every_ Sugargame activity until you find something that matches.

**Comment by quozl** [comment]
Reviewed again.

* [x] `sugargame/canvas.py` has an unintended change unrelated to the looping; here's the diff relative to sugargame repository;

```diff
--- ../sugargame/sugargame/canvas.py    2018-12-03 13:07:42.514078635 +1100
+++ sugargame/canvas.py 2019-02-06 17:48:55.374669130 +1100
@@ -9,7 +9,8 @@
 
 
 class PygameCanvas(Gtk.EventBox):
-    def __init__(self, activity, main=None, modules=[pygame]):
+    def __init__(self, activity, pointer_hint=True,
+                 main=None, modules=[pygame]):
         Gtk.EventBox.__init__(self)
 
         global CANVAS
```

* [x] sugargame repository has changes since; https://github.com/sugarlabs/sugargame/commit/bdc8bea2ff3961a5aea5a7ddfedb49c624c26316

Also looked at the suggestion I made in earlier comment;

> compare the program flow and structure between the Sugargame V1.2 test activity and this activity, working to change the structure accordingly

When I compared `TestActivity.py` to `activity.py` some small differences were fixed but the problem did not go away; see https://github.com/sugarlabs/iknowEditor/commit/27941b241cec94e192e714060deadb7d5479be79.

When I compared `TestGame.py` to `conozco.py` several differences were apparent, and I worked on them until the loop problem went away;

* use the `run` method name, and exit the loop when stop button is pressed; https://github.com/sugarlabs/iknowEditor/commit/6048899950f6d6895aedf95e5ff25e7ef9d1dffb
* use a frame rate limiter; https://github.com/sugarlabs/iknowEditor/commit/5cc0ec42550dbc2f5c6b610ea768bb1ae71b7bf1

Please cherry-pick these patches.  They are uploaded to [branch 2019-02-19-pull-3-review](https://github.com/sugarlabs/iknowEditor/commits/2019-02-19-pull-3-review).

**Comment by chimosky** [comment]
> - [ ]  `sugargame/canvas.py` has an unintended change unrelated to the looping; here's the diff relative to sugargame repository;

Fixed in 0a5ffa7. Thanks.

> Please cherry-pick these patches. They are uploaded to [branch 2019-02-19-pull-3-review](https://github.com/sugarlabs/iknowEditor/commits/2019-02-19-pull-3-review).

Changes applied, activity runs but shows a blank screen on startup and the logs don't show anything

**Comment by chimosky** [comment]
Tested again and activity runs as expected.

**Comment by quozl** [comment]
Thanks.  Reviewed.

Last working GTK 2 version of this activity was https://github.com/sugarlabs/iknowEditor/commit/a6551b981820c856f3d0d34f3c9692d32384ec96.  The activity at this point in history works as described in new issue on teacher documentation just added.  It also has a CPU loop, but adding the frame rate limitation fixes it.

Closest match to Sugargame sources at the above commit is https://github.com/sugarlabs/sugargame/commit/8254afb5ed18706ffb90210747c6beac4d9cf98e.

Our [GTK 3 Porting Guide](https://github.com/sugarlabs/sugar-docs/blob/master/src/gtk3-porting-guide.md) relates.  I've adjusted it to remind you that the activity should be tested on GTK 2 before porting, and this test would tell you how it should work.  It should work no differently on GTK 3 unless there is good reason.

Tested e14b39b; it no longer works properly;

* [x] the _Add a point_ button does not add a point,
* [x] entries are added to the table without coordinates,
* [x] the canvas containing the map does not refresh after the tooltips of the buttons are hidden.

Another port to GTK 3 of an activity related to this one; https://github.com/sugarlabs/iknowMadagascar/commit/5de78baca2daebe483bcc35912d254c77f2416f4.

**Comment by quozl** [comment]
GTK 2 screenshot after adding two points;

tmp

**Comment by chimosky** [comment]
> Our [GTK 3 Porting Guide](https://github.com/sugarlabs/sugar-docs/blob/master/src/gtk3-porting-guide.md) relates. I've adjusted it to remind you that the activity should be tested on GTK 2 before porting, and this test would tell you how it should work. It should work no differently on GTK 3 unless there is good reason.

I tested before trying to port and it worked fine. It doesn't work differently from the GTK3 ongoing port, except a few widget design differences - which is expected -.

>  - [x] the _Add a point_ button does not add a point,

It does add a point, but `remove point` removes the point but also throws an error

screenshot from 2019-02-20 11-15-39
This is a screenshot of the current port with two added points


Error thrown by `remove point`, although this happens when trying to remove a point when an image wasn't added - this is expected as the code assumes that they'll always be a `Surface` -.
```
Traceback (most recent call last):
  File "/home/ibiam/Activities/iKnowEditor/activity.py", line 141, in _remove_point
    self._update_points()
  File "/home/ibiam/Activities/iKnowEditor/activity.py", line 152, in _update_points
    self.actividad.update_points(l)
  File "/home/ibiam/Activities/iKnowEditor/conozco.py", line 481, in update_points
    self.pantalla.blit(self.fondo, (shift_x, shift_y))
TypeError: argument 1 must be pygame.Surface, not None
```

https://github.com/sugarlabs/iknowEditor/blob/a6551b981820c856f3d0d34f3c9692d32384ec96/conozco.py#L481-L493

Fixed in bc41418.

> - [x] entries are added to the table without coordinates,

As shown in the screenshot, entries can be added but you'll have to click on `Position` column of the city you wish to add coordinates

> - [ ] the canvas containing the map does not refresh after the tooltips of the buttons are hidden.

When you say refresh, what do you mean? In mine, there are no noticeable changes when the tooltips become visible and when they hide.

> Another port to GTK 3 of an activity related to this one; [sugarlabs/iknowMadagascar@5de78ba](https://github.com/sugarlabs/iknowMadagascar/commit/5de78baca2daebe483bcc35912d254c77f2416f4).

I'll take a look thanks

**Comment by chimosky** [comment]
@quozl kindly review.

**Comment by chimosky** [comment]
@quozl, anything more for me to do here?

**Comment by quozl** [comment]
Tested bc41418ea6f773708d346397ecee354daa026f69;

* [x] many errors occur

```log
Traceback (most recent call last):
  File "/usr/share/sugar/activities/IknowEditor.activity/conozco.py", line 531, in run
    self.parent._add_coor(pos)
  File "/usr/share/sugar/activities/IknowEditor.activity/activity.py", line 145, in _add_coor
    self.labels_and_values.update_selected_value(pos)
  File "/usr/share/sugar/activities/IknowEditor.activity/points_list.py", line 96, in update_selected_value
    self.model[path][0] = data
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 1091, in __setitem__
    self.model.set_value(self.iter, key, value)
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 991, in set_value
    value = self._convert_value(column, value)
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 875, in _convert_value
    return GObject.Value(self.get_column_type(column), value)
  File "/usr/lib/python2.7/dist-packages/gi/overrides/GObject.py", line 218, in __init__
    self.set_value(py_value)
  File "/usr/lib/python2.7/dist-packages/gi/overrides/GObject.py", line 271, in set_value
    (py_value, type(py_value)))
ValueError: Expected string or unicode but got (235.15625, 88.17431640625)<type 'tuple'>
could not convert string to float: 

1551332044.462904 ERROR root: Event queue full!
1551332044.468510 ERROR root: Event queue full!
1551332044.476390 ERROR root: Event queue full!
1551332044.484381 ERROR root: Event queue full!
1551332044.492344 ERROR root: Event queue full!

Traceback (most recent call last):
  File "/usr/share/sugar/activities/IknowEditor.activity/sugargame/event.py", line 115, in _visibility_cb
    self.update_display()
  File "/usr/share/sugar/activities/IknowEditor.activity/sugargame/event.py", line 98, in update_display
    pygame.event.post(pygame.event.Event(pygame.VIDEOEXPOSE))
pygame.error: Event queue full

Traceback (most recent call last):
  File "/usr/share/sugar/activities/IknowEditor.activity/sugargame/event.py", line 105, in _resize_cb
    pygame.event.post(evt)
pygame.error: Event queue full

Traceback (most recent call last):
  File "/usr/share/sugar/activities/IknowEditor.activity/sugargame/event.py", line 112, in _quit_cb
    pygame.event.post(pygame.event.Event(pygame.QUIT))
pygame.error: Event queue full

Traceback (most recent call last):
  File "/usr/share/sugar/activities/IknowEditor.activity/sugargame/event.py", line 109, in _screen_changed_cb
    self.update_display()
  File "/usr/share/sugar/activities/IknowEditor.activity/sugargame/event.py", line 98, in update_display
    pygame.event.post(pygame.event.Event(pygame.VIDEOEXPOSE))
pygame.error: Event queue full
```

* [x] still cannot add a point; the procedure which works with https://github.com/sugarlabs/iknowEditor/commit/a6551b981820c856f3d0d34f3c9692d32384ec96 is;
  * click on _Add a point_ button; a line is added to the table,
  * click on the map; a red dot is added to the map and the position is updated on the table.

**Comment by AlanJAS** [comment]
The problem is the list expect a text and we pass the pos tuple directly. You can use this workarround to fix that and get the activity works again.

[0001-workarround.txt](https://github.com/sugarlabs/iknowEditor/files/2926833/0001-workarround.txt)

**Comment by quozl** [comment]
Thanks, @AlanJAS!

**Comment by chimosky** [comment]
Thanks @AlanJAS, @quozl kindly review.

**Comment by quozl** [comment]
Thanks.  Reviewed.  Tested.

**Pull request merged**
