### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by ayushnawal**

### CODE REVIEW

**Comment by quozl** [comment]
Only Browse supports download and automatic install of activity bundles.

**Comment by ayushnawal** [comment]
I thought of directing the user directly to the **i know page** by updating the link so that there is no need to search in [Activities](https://activities.sugarlabs.org/en-US/sugar/)

**Comment by quozl** [comment]
Yes, I figured that out from 463be54.  At the time we began adding README.md files, it wasn't clear if the URLs would remain stable, so I said to search.  I guess we have reached a point where the URLs are likely to remain stable, so up to you; either be consistent or save search time.

**Comment by ayushnawal** [comment]
I see, closing the pull request.
Thanks :)

**Comment by quozl** [comment]
8f53b6536f8903b2a04add10046e1109b8754925

**Pull request closed without merging**
