### PR TITLE
v2

### LINKED ISSUE #4: Assumes writable source directory
Save data button tries to create a file `salida.py` in the source directory.  This does not work when the source directory is system-wide `/usr/share/sugar/activities/IknowEditor/`.

* [ ] write the file to home directory or journal.

### PR DESCRIPTION
**Pull request by chimosky**
Fixes #4, #6

### CODE REVIEW

**Comment by quozl** [comment]
Is this proposed as a fix for https://github.com/sugarlabs/iknowEditor/issues/4?

**Comment by chimosky** [comment]
It's a proposed fix for #6, I decided to add it here.

**Comment by quozl** [comment]
I'm confused.

**Comment by chimosky** [comment]
I'm working on making a release, so I decided to fix that here.

**Comment by quozl** [comment]
Oh, I see, thanks.  In that case;

* fixes https://github.com/sugarlabs/iknowEditor/issues/4
* fixes https://github.com/sugarlabs/iknowEditor/issues/6

... so that they automatically close.  :grin:

**Comment by Aniket21mathur** [comment]
@chimosky still working on this? Thanks!

**Comment by chimosky** [comment]
@Aniket21mathur yeah I'm still working on it.

**Comment by chimosky** [comment]
Activity image and tar ball at http://people.sugarlabs.org/ibiamchihurumnaya/

**Comment by chimosky** [comment]
@quozl kindly review.

**Comment by quozl** [comment]
Thanks.  Reviewed.  Please commit the activity.info change and push?

**Comment by chimosky** [comment]
I plan on uploading to ASLO and add @AlanJAS as an author.

**Pull request merged**
